name: ITeation
favicon: null
layout_spectrum: 0.50508
typography_spectrum: 0.08999078534543514
title: 'Managed IT Services Expert IT consulting '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#4d734e'
    - '#b5b5b5'
    - '#000100'
    - '#ade204'
  brandStrength: 0.5
  lightness: 0.19372020498849452
  saturation: 0.7668831830378622
  rhythmicContrast: 0.18319263379089534
purpose: []
